### ISSUE TITLE
a few general questions before I start training ....

### ISSUE THREAD

**Issue by vince62s** [marian-nmt/marian#143]
I understand we set the size in GPU memory, eg 10000 for 10GB, tuto says "to leave 2GB on a 12GB memory". On GTX 1080ti ram is 11GB, should we set 9000 instead ?

Also if training is on multi gpu, eg gtx 1080 + gtx 1080ti, we need to set the  lowest one or can it adapt to each GPU Ram ?

does it support fp16 to fit bigger models ?

did you notice, as for T2T, that hyper parameters have a big impact on the results (batch size, number of gpu for instance)

I'll give it a try shortly.

**Comment by emjotde** [comment]
1) RAM: that's actually a bit more complicated. There is a FAQ entry where I tried to elaborate a bit:
https://marian-nmt.github.io/faq

"How do I chose mini-batch size, max-length and workspace memory?"

2) Multi-gpu will use the same amount of memory on each GPU. So in your case the minimum. 

3) No fp16 yet. A good way to save memory is to use `--tied-embeddings-all`, if you can use common vocabularies for source and target, otherwise `--tied-embeddings`

4) For shallow RNN models it does not seem to matter that much and standard parameters are mostly fine. For anything that's deeper it does indeed matter. The transformer model (t2t) is very peculiar in this case and our implementation also needs specific hyper-parameter. I did see though that the transformer hyperparams are a pretty good choice in general for deeper models.

**Comment by vince62s** [comment]
thanks.
one last thing before I close this.
I saw a "lm" model type.
At inference, what is supported right now ? spit the next word ? log likelihood / ppl ?

**Comment by emjotde** [comment]
I use it either for rescoring with `marian-scorer` or in ensembles with normal models. You can do 

`marian-decoder -m model.tm.npz model.lm.npz --weights 0.8 0.2 ...`

and play around with it. I did not use it much for translation, but very successfully for a number of monolingual tasks. Used on it's own I think it will only generate the same sentence over and over, actually never tried that.
