### ISSUE TITLE
docker images fail to build

### ISSUE THREAD

**Issue by aoboturov** [marian-nmt/marian#153]
Try to build with gcc 4.9, 5 and 6. Have the following error on all combinations:

`c++: internal compiler error: Killed (program cc1plus)`

Both GPU and CPU versions fail.

https://github.com/marian-nmt/marian/tree/master/scripts/docker

**Comment by aoboturov** [comment]
To test against particular compiler version you could use the following set up docker image:

```
FROM ubuntu:16.10
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    binutils bzip2 ca-certificates cmake-data cpp-4.9 gcc-4.9 g++-4.9 dh-python dpkg-dev \
    git python3.5 python-pip libboost-all-dev cmake zlib1g-dev wget unzip \
  && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 10 \
  && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 10 \
 	&& rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip
```

**Comment by emjotde** [comment]
Pinging @alvations You did the Docker images, right?

**Comment by aoboturov** [comment]
It's likely a memory issue:

- compilation on machine with 6Gb fails
- compilation on machine with 16Gb passes

**Comment by aoboturov** [comment]
Even though the compilation passes, linking fails. Looks pretty much like https://github.com/marian-nmt/marian/issues/147 - gonna try to build boost 1.64 from scratch as suggested.

**Comment by aoboturov** [comment]
CMake and boost versions are tied together, so you have to upgrade minimal CMake version every time you update boost.

**Comment by emjotde** [comment]
Concerning Cmake and Boost: Never had to do that. Cmake will spew out a few warnings but will usuall keep working. Recently confirmed with Boost 1.66 and Cmake 3.5.

**Comment by aoboturov** [comment]
Do you have build server or something? Because "confirmed on my local" machine does not give any guarantees...

**Comment by alvations** [comment]
@aoboturov did you change the base version of the docker image to Ubuntu 16.10 instead of 16.04? For 16.04, I've tested and successfully deployed servers for training + decoding. Let me test around and see whether it's possible to packaged that into the docker with 16.10.  

The Dockerfile builds the image for both training and decoding but if you're deploying for decoding, you can minimize dependencies without the `*-dev`. 

@emjotde is it possible to do the moses `bjam` trick and just install a local boost and then link automatically? Or is that just too cumbersome?

**Comment by alvations** [comment]
You could force the default gcc in Ubuntu 16.10 plays nice with a custom installed libboost 1.58, but it works only for CPU:

- Ubuntu 16.10
- libboost 1.58
- gcc 6.2.0


```
FROM ubuntu:16.10

MAINTAINER Mama <ma@ma.com>
LABEL description="Basic Marian docker container for Ubuntu"

# Install some necessary tools.
RUN apt-get update && apt-get install -y \
                build-essential \
                git-core \
                pkg-config \
                libtool \
                zlib1g-dev \
                libbz2-dev \
                cmake \
                automake \
                python-dev \
                perl \
                libsparsehash-dev \
                wget \
            && rm -rf /var/lib/apt/lists/*

RUN wget http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz
RUN tar -zxf boost_1_58_0.tar.gz
WORKDIR boost_1_58_0/
RUN ./bootstrap.sh
RUN ./b2 install
WORKDIR /

RUN git clone https://github.com/marian-nmt/marian

ENV MARIANPATH /marian

WORKDIR $MARIANPATH
RUN mkdir -p build
WORKDIR $MARIANPATH/build
RUN cmake $MARIANPATH && make -j
```

Let me test with GPU and CUDA 8.0. It should work, I've a local machine doing that but I'll try with the Docker image.

**Comment by aoboturov** [comment]
Just to compare:

https://github.com/aoboturov/aoboturov-deephack-babel-qualification/blob/master/marian-nmt/Dockerfile.marian

was the only default combination which actually worked (i.e. compiled and passed the runtime) for me.

**Comment by alvations** [comment]
Did CUDA 8.0 worked with Ubuntu 17.10? 

Or are you using only the CPU version?

**Comment by aoboturov** [comment]
CPU only version

**Comment by alvations** [comment]
Ah, that makes it simple. Any ubuntu version for the docker base image would work as long as you have the dependencies installed:

```
# Install some necessary tools.
RUN apt-get update && apt-get install -y \
                build-essential \
                git-core \
                pkg-config \
                libtool \
                zlib1g-dev \
                libbz2-dev \
                cmake \
                automake \
                python-dev \
                perl \
                libsparsehash-dev \
                wget \
            && rm -rf /var/lib/apt/lists/*
```

IMHO, I think it's cleaner to support Dockerfiles for only LTS distro versions so that it's easier to maintain. The next one is 18.04 in April https://wiki.ubuntu.com/Releases. 

It might be better to update the Dockerfiles to support 18.04 instead of 17.10. Also lets wait till nvidia officially supports the Ubuntu version with the CUDA magic all packed in before upgrading the Dockerfile. 

---- 

@aoboturov BTW, nice repository: https://github.com/aoboturov/aoboturov-deephack-babel-qualification

**Comment by aoboturov** [comment]
@alvations thx for checking it out :)
