### ISSUE TITLE
recent amun versions segfault with some beam size settings

### ISSUE THREAD

**Issue by oraveczcsaba** [marian-nmt/marian#164]
Including the latest version (8c119e7) we get segfaults when decoding with amun with lower than default beam sizes (<12).
``
amun -m model.npz -s ./clean-bpe.en.json -t ./clean-bpe.de.json -b 10
``
the
Segmentation fault
``
amun -m model.npz -s ./clean-bpe.en.json -t ./clean-bpe.de.json -b 12
``
the
Search took 0.025s
Best translation 0 : die
die

Older versions (eg. 12897cc) do not seem to have this problem. 
I put the resources here:
http://budling.nytud.hu/~oravecz/download/endesample.zip

**Comment by hieuhoang** [comment]
Can you try adding the following argument
   --use-fused-softmax false

Hieu Hoang
Sent while bumping into things

**Comment by oraveczcsaba** [comment]
By a quick test, it seems to help.

**Comment by hieuhoang** [comment]
Probably a edge case bug in my code. I'll take a look assert it in a few
weeks

Hieu Hoang
Sent while bumping into things

On 12 Mar 2018 12:31 p.m., "Csaba Oravecz" <notifications@github.com> wrote:

By a quick test, it seems to help.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/marian-nmt/marian/issues/164#issuecomment-372279465>,
or mute the thread

**Comment by hieuhoang** [comment]
could you please share your model again. Will try to look into the bug

**Comment by oraveczcsaba** [comment]
It should still be available at the link in my first post. Let me know if it does not work.

**Comment by hieuhoang** [comment]
doesn't work

**Comment by oraveczcsaba** [comment]
sorry, i mixed up a directory. now it is there.

**Comment by hieuhoang** [comment]
thanks. it looks like an edge case when the target vocab size is small. I'll debug a bit more and make sure it doesn't happen again.

Carry on using  --use-fused-softmax false. Fused softmax isn't of much benefit with small vocab size anyway
