### ISSUE TITLE
Transformer attention matrices and word alignments 

### ISSUE THREAD

**Issue by tomsbergmanis** [marian-nmt/marian#198]
Are you planning to implement functionality to get word alignments out of transformer attention matrices? 
Word alignments are often important to restore the source side document markup.

**Comment by emjotde** [comment]
Yes, quite high on my to do list. We recently added this for rnn models, and are now thinking how to approach this for the transformer. It's a bit more involved, as the transformer has basically 6 x 8 different alignment matrices. And in theory none of these has to be very useful for word alignment purposes.

**Comment by alvations** [comment]
Was thinking the same and then I realize that attention becomes complicated in ensembled models... 

Is that why the `marian-decoder` has not `--return-nematus-alignments` option? Is it even possible to get attention alignments for ensemble and what would they mean if it meant anything at all? 

Since the individual models might be on different scale and attention weights needs some sort of normalization before a combination (average?) ?

**Comment by tomsbergmanis** [comment]
@emjotde Thank you for your answer. 
It would be very useful if there was a way to do it as it would mean that transformer models could be more easily deployed in commercial scenarios of document translation.
Thank you, 
Toms

**Comment by emjotde** [comment]
I am looking at the attention matrices now. 

I think without using guided alignment, you will have a very time to use them for anything. Averaging for instance the attention weights across all heads of the first attention block nearly always results in the largest weight being on the end of sentence token. This is most likely caused by the fact, that attention uses this as a parking position. You have heads which look like normal attention, but is it impossible to guarantee that this will always be the same head for different models. 

Guided attention would need to be used with one of the heads.

**Comment by emjotde** [comment]
@alvations I don't see any issues with ensembles and attention. Just choose one of the models. We just added alignment output for rnn models to marian-decoder and looking now how to do this in a smart way for transformer.

**Comment by tomsbergmanis** [comment]
Hi @emjotde , 
I actually found a simple way to get word alignments Transformer attention matrices for Sockeye (See code [here](https://github.com/tilde-nlp/sockeye/blob/transformer-attention) )
Specifically, I compute transformer attention probabilities as [the average attention probabilities over all attention heads in all](https://github.com/tilde-nlp/sockeye/blob/a77dccbec8de2a3b1e26ce63e0c3f32b54a80c1f/sockeye/decoder.py#L346)

To evaluate the resulting attention probability matrices I used them as a basis for discrete word alignments. Then I compared the resulting alignments against:

- alignments obtained from MLSTM attention matrices,
- alignments by FastAlign.
When conducting a human evaluation, I found that resulting word alignments are on average judged as acceptable as word alignments from MLSTM attention matrices and strictly better than alignments by FastAlign.

Maybe you could implement the same for Marian? 
Best,
Toms

**Comment by emjotde** [comment]
@tomsbergmanis Weird. That really should not work :)

**Comment by tomsbergmanis** [comment]
Well, it does. :D

**Comment by emjotde** [comment]
Yeah, that's actually very troubling, cos there is not good reason for it to work. I also talked to the Amazon guys about that, we kind of agreed that without some special magic there is no guarantee that there is anything meaningful in those alignment matrices.

**Comment by emjotde** [comment]
The current version of master in https://github.com/marian-nmt/marian-dev has trainable alignment constraints for a single attention head in transformer now. It looks pretty good, nice and peaky. 

More information in this issue: https://github.com/marian-nmt/marian-dev/issues/277

I am convinced that this is the right way to do that and your way can backfire any moment, especially during peer review :)
