### ISSUE TITLE
How to run multi-node in 1.7.0?

### ISSUE THREAD

**Issue by WenbinHou** [marian-nmt/marian#244]
I would like to run example/transformers with mpirun in 2 nodes, but without forturn.

Seems multi-node mode is broken. I can't even specify witch GPU devices to use on each node. (fails in `common/config_validator.cpp`)

How to correctly pass `--devices` / `--num-devices` with `--multi-node`?

TIA!

**Comment by frankseide** [comment]
You will need an RDMA-enabled Infiniband connection, otherwise it will not be efficient.

You also need to compile Marian with MPI support, i.e. you need to say `-DUSE_MPI=ON` when calling `cmake`.

To run, please specify the devices that each node should use locally. If each node has 4 GPUs, you specify `--devices 0 1 2 3` (or alternatively `--num-devices 4`, which means the same thing). Use `--sync-sgd`, not `--multi-node`. Then run the executable with `mpirun`. Here is a `mpirun` command line I used (note that I don't really understand all `mpirun` options, some are try-and-error):
```
mpirun --npernode 1 \
  --mca oob_tcp_if_exclude docker0,lo,ib0,ib1 --mca btl self,sm,tcp --mca btl_tcp_if_exclude docker0,lo,ib0,ib1 \
  -x OMP_NUM_THREADS=2 \
  -x NCCL_IB_DISABLE=0 -x NCCL_SOCKET_IFNAME=ib0 -x NCCL_DEBUG=INFO -x CUDA_CACHE_DISABLE=1 -x NCCL_IB_TIMEOUT=20 -x NCCL_IB_RETRY_CNT=30 \
  -x LD_LIBRARY_PATH="~/marian-dev/build:$LD_LIBRARY_PATH" \
  --host $hosts  --bind-to none \
~/marian-dev/build/marian ...
```

Your log should contain messages like `MPI rank 0 out of 2`.
