### ISSUE TITLE
difference in words per second in documentation

### ISSUE THREAD

**Issue by wmpauli** [marian-nmt/marian#309]
Hi,

Why are the tokens per second for multi-gpu training in the [documentation](https://marian-nmt.github.io/features/) (bottom) so different from the [Marian demonstration paper](http://www.aclweb.org/anthology/P18-4020)?

Thanks!

**Comment by emjotde** [comment]
Hi, 

mostly because we are continuously optimizing things and the paper is
older than the numbers on the web page. I think that particular change
was due to the introduction of a caching mechanism for a transformer,
possibly also due to using NCCL, I don't quite remember. Most likely
current Marian (v1.8 from the marian-dev repo) is again going to be
faster than the numbers on the homepage; to be updated soon. So at the
moment I would guess none of these numbers are accurate anymore.  

W dniu 2020-01-12 13:45, Wolfgang Pauli napisał(a):

> Hi, 
> 
> Why are the tokens per second for multi-gpu training in the documentation [1] (bottom) so different from the Marian demonstration paper [2]? 
> 
> Thanks! 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [3], or unsubscribe [4].

  

Links:
------
[1] https://marian-nmt.github.io/features/
[2] http://www.aclweb.org/anthology/P18-4020
[3]
https://github.com/marian-nmt/marian/issues/309?email_source=notifications&amp;email_token=AAIIN5MKNP6VR2L22D53HD3Q5OFPPA5CNFSM4KF2B6L2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IFTOYEA
[4]

**Comment by wmpauli** [comment]
Awesome. Thank you.

**Comment by emjotde** [comment]
Now I am actually curious what the current numbers are. I will have a look if I can find the correct benchmark and the same set of GPUs.
