### ISSUE TITLE
LSTM cell for Amun and Marian

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian#78]
Long time planned, but always move back due to other task. It seems there is increased interest for a proper LSTM cell, so let's make this happen.

**Comment by emjotde** [comment]
For training, I have now a very slow protoype in Marian: 

https://github.com/marian-nmt/marian-train/blob/lstm/src/layers/rnn.h#L398

It does not work for translation yet with s2s, as I need to figure out a good way how to adjust the cell state for beam search. We will have the exact same problem in Amun, as we need to select the hypotheses now for two states (or we concatenate the states, then it solves itself.)

Some questions:
* How is the cell state initialized in the decoder, just resuing the normal start state?
* Which state goes into the attention mechanism in the conditonal attention cell, the output state or the cell state or both? I suppose the output state.

**Comment by rihardsk** [comment]
Here are some of my thoughts on the implementation in Amun.

### Managing the state
Concatenating the states solves only some of the problems. The [`Decoder`'s `Decode` method](https://github.com/marian-nmt/marian-train/blob/lstm/src/layers/rnn.h#L398) would then need to work differently for GRU, and LSTM. If we wan't to condition the attention mechanism on the RNN cells output I think we should probably introduce _output_ as a separate concept. GRU would then be a special case for which the cell's output is the same as its state.

### Initializing
In our implementation in Nematus we did the reverse - initialized the cell's state with zeros and used the normal start state to initialize the cell's output state. It worked well but I'd imagine that doing the reverse would work too and I don't know what's the right approach. Maybe make this configurable with some sort of a bridge class like in [google/seq2seq](https://github.com/google/seq2seq/blob/master/seq2seq/models/basic_seq2seq.py#L87)?

### Masking
I haven't encountered masking in Amun. I guess this is relevant only to training(?).

### Decoder's implementation
There is another issue with the [`Decoder`'s `Decode` method](https://github.com/marian-nmt/marian-train/blob/lstm/src/layers/rnn.h#L398) - how do we combine the attended context with the LSTM's output? In our Nematus implementation we basically just swap the pre-attention GRU with LSTM and leave the rest as is. So something like:
```Python
def decoder_step(...):
    next_hidden_cell_state, hidden_output_state = LSTM_step(hidden_cell_state_, hidden_output_state_, embeddings)
    attended_context = attention(hidden_output_state, source_context)
    next_hidden_output_state = GRU_step(hidden_output_state, attended_context)
    return next_hidden_cell_state, next_hidden_output_state
```
But I have seen another implementation where the `attended_context` and `hidden_output_state` are simply concatenated and run through a feed-forward layer. One could also imagine, e.g., using an LSTM for the second part as well.

The good thing here is that managing the cell's output separately as mentioned above should support all of the mentioned variants.

**Comment by tomekd** [comment]
HI @rihardsk ,

Amun uses masking, but only in GPU backend. It's required for batch translation because source sentences have various lengths and the attention need to know that to compute the source context.

Why didn't you use context vector as the input to the second LSTM?
```
def decoder_step(...):
    next_hidden_cell_state, hidden_output_state = LSTM_step(hidden_cell_state_, hidden_output_state_, embeddings)
    attended_context = attention(hidden_output_state, source_context)
     next_hidden_cell_state_2, hidden_output_state_2 = LSTM_step(hidden_cell_state_, hidden_output_state_, attended_context)
```

**Comment by emjotde** [comment]
@tomekd I guess you mean cell state vector, not context. What you described is what I am doing now in my experiments. Seems to work alright.

**Comment by tomekd** [comment]
@emjotde : I mean to use the output vector from attention as an input to the second LSTM. Later, use the h state from LSTM to the readout layer.

**Comment by emjotde** [comment]
Yes, but he's doing that part with the attention context.

**Comment by emjotde** [comment]
What @tomekd described is what I am doing now for testing. LSTM everywhere seems to converge a bit slower but then again this is perhaps not surprising.

**Comment by emjotde** [comment]
@rihardsk With the architecture you described, are you seeing quality gains? Did you test that on a public data set?

**Comment by rihardsk** [comment]
@tomekd at the time of implementing it I didn't  consider the second GRU as a separate thing but more like a part of the attention mechanism. So it basically became a question of how to combine the `attended_context` with the `hidden_output_state` from the first LSTM, and I decided to leave it as is. It worked well so it stayed that way.

Now looking at it it seems that doing LSTM everywhere might be a better idea since it might make it easier for the network to combine the post-attention outputs with the cell state. But whatever the implementation is 

@emjotde so then the convention would be to pass the first element of the state vector to the attention mechanism? I see that the `applyState()` method has been like that for a while now and this just needs implementing in Amun right?

**Comment by emjotde** [comment]
For the moment I would refrain from modifying amun until I have a working implementation in marian (I am getting closer). I would like to mimic the solution in marian then as closely as possible in amun, otherwise we will get crazy with future changes. We also plan to add multi-layer support and the new deep rnn cells from Nematus, so some better design is required. 

In the moment I came up with a solution where a special RNNState class exists, and the code around that is agnostic w.r.t what's going on in there. Only the specific cell (LSTM, GRU or whatever) knows what to extract from there and how to fill it.

**Comment by rihardsk** [comment]
@tomekd I don't have a comparison between using GRU and LSTM for the post-attention part. Don't know which is better.

We do see quality gains when comparing the regular Nematus implementation with the one I described, but using [multiplicative LSTM](https://arxiv.org/abs/1609.07959) cells instead of plain LSTM. When doing experiments for our WMT 2017 submission for English-Latvian and Latvian-English we saw a 1 BLEU increase.

**Comment by emjotde** [comment]
mLSTM: easy enough to add. Will take a look at that too. Currently my LSTM is 5 BLEU worse :)

**Comment by rihardsk** [comment]
@emjotde using a RNNState class as you described sounds good. Ok, let's wait for an implementation in Marian.

@emjotde yes, there should be no problems doing mLSTM after the groundwork is done. Our experiments with plain LSTM actually also didn't go that well. Trying out deep LSTM's with [Google's seq2seq](https://github.com/google/seq2seq) gave us around -2 BLEU comparing to the Nematus baseline (didn't run it too long though), but note that in the post-attention part they use only a simple feed-forward layer. Trying out plain LSTM in Nematus with the architecture described above gave us -1 BLEU, but there was a bug in the implementation so it probably should have scored higher (we also didn't run it for too long).

**Comment by emjotde** [comment]
Reminder to self: do not use dropout on the cell state. That was causing the 5 BLEU points loss.

**Comment by emjotde** [comment]
@rihardsk Did you use the multiplicative LSTM everywhere instead of the GRU or just the first cell in the decoder?

**Comment by rihardsk** [comment]
@emjotde encoder, and only the first cell in the decoder.

**Comment by emjotde** [comment]
Thanks. Will try that in a moment. Our normal LSTM in Marian has now basically identical performance to the GRU for our RO-EN WMT data set.

**Comment by emjotde** [comment]
@rihardsk How are you using amun? Have you maybe tried `s2s` instead? `s2s` has now lstm support as marian has it.

**Comment by rihardsk** [comment]
@emjotde i have only used `amun` with models trained with `Nematus`. Haven't tried `s2s` yet.

What's the plan on going forward with the implementation in `amun`?

**Comment by tomekd** [comment]
Sorry, I have a lot of work now, and probably for next two weeks.

**Comment by rihardsk** [comment]
Has anyone started work on the implementation in Amun? If not I would like to do it. Here are my thoughts on the issue.

I took a look at the implementation in `marian-train` and I think the Amun implementation steps should look something like:
1. introduce a `Cell` class and make `GRU` and `LSTM` inherit from it, the class would expose only the `GetNextState()` and `GetStateLength()` pure virtual methods;
2. refactor the `Encoder` and `Decoder` to use the `Cell` instances instead of `GRU<Weights>`;
3. refactor the `EncoderDecoder`'s constructor to initialize the `Encoder` and `Decoder` with the appropriate cell type according to the `config` object;
4. refactor `Cell::GetNextState()` to use a `CellState` class for inputs and outputs similar to how it's done in `marian-train`;
5. implement the actual LSTM cell.

**This raises some questions:**

I am not really sure yet how to do `3.`.  Should we make the `Encoder` and `Decoder` into class templates and specify the cell type as the template parameter? But then how would the correct cell type be initialized and loaded with parameters from `model`? Also this slightly defies the point of creating the `Cell` class.

Or should we initialize the correct `Cell` instances in the `EncoderDecoder`'s constructor and make everything from there work with the interface provided by `Cell`?

I think I prefer the second option but maybe there is a better way and/or I'm missing something?

Another question is what was the reason for having a class template `GRU<Weights>` instead of a simple `GRU` class? I see that the `Weights` template parameter plays a role in deserializing the correct weights from the `model`, but this could have also been done by having a single `GruWeights` class and make all of the different `DecGRU1`, `DecGRU2`, and similar classes in `model.h` inherit from `GruWeights`, or do something similar. Are there any other reasons for using class templates here? The reason I'm asking is that these details kind of go in had with deciding on the point `3.` above.

When implementing the point `4.` should we make all the relevant methods pass the `CellState` as a return value as it is done in `marian-train` or should we stick to passing along `CellState&` references via method inputs as it is done currently? To reduce the amount of work I think I'd prefer the later.

What are your thoughts on the whole matter?

**Comment by hieuhoang** [comment]
Yes, it would be great if you can do it.
  1. template enc/dec or Cell class - this was also a dilemma in Marian. I think it now uses Cell class as it's easier to read and debug. I agree with you - the Cell class is prob a better way to go.
2. GRU<Weights> - I agree, the template design looks overcomplicated, it was prob designed with something else in mind.
3. CellState - up to you.
So in summary, you will have to evolve amun & its RNN framework to incorporate LSTM, this was also required in Marian. It's not simply a matter of plonking LSTM in, but it should be interesting and you sound like you've looked at it and considered the strategies so I would say go for it! If you do it on github, I'll give you a hand where I can

**Comment by emjotde** [comment]
In Marian I'm actually moving away from templates in the high-level interface in favor of good old polymorphism. 

Cell state: What I did now is to assume there is always a cell state and I just pass `std::nullptr` if there isn't a meaningful one as for the GRU. You can reuse the forward kernels for the FastLSTM cell directly, I believe. I can help with that.

**Comment by emjotde** [comment]
@rihardsk Another thing is, if you are using only the GPU version of Amun, you might want to start looking at the s2s translator, speed different is now down to 10-15% in the version in current master of `marian-train` and that already has LSTMs now. Batched decoding is still missing, but basically next on my TO-DO list.

**Comment by rihardsk** [comment]
Thanks for the comments. I have started work on the LSTM implementation. See #104. This is taking a bit longer than thought but I expect it to pick up pace from here on.

@emjotde thanks for the info, but my main interest is running Tilde's WMT models, which beside MLSTM also require factored inputs to run, so `marian-train` can't be used right now. (Factored inputs are the next thing I plan on implementing.)

**Comment by emjotde** [comment]
I guess the discussion has moved to the pull request, so I am closing this.
